#!/usr/bin/env python3
"""
Firmware Build Post-Processing Script

Copies compiled ESP32 firmware files to:
1. esp32-installer/ (for serial flashing via esptool)
2. rgfx-hub/assets/esp32/firmware/ (for OTA updates from Hub)

This script runs automatically after PlatformIO builds via extra_scripts in platformio.ini.
Can also be run standalone for manual deployment.
"""

import shutil
import hashlib
import json
from datetime import datetime, timezone
from pathlib import Path

# Files to copy for serial flashing (esp32-installer)
FIRMWARE_FILES = [
    {'name': 'firmware.bin', 'address': '0x10000'},
    {'name': 'bootloader.bin', 'address': '0x1000'},
    {'name': 'partitions.bin', 'address': '0x8000'},
]


def get_version(project_root):
    """Extract version from version.h header file (generated by inject_version.py)"""
    version_h = project_root / 'esp32' / 'src' / 'version.h'

    # Read version.h and extract RGFX_VERSION value
    with open(version_h, 'r') as f:
        for line in f:
            if line.startswith('#define RGFX_VERSION'):
                # Extract version string: #define RGFX_VERSION "1.0.0" -> 1.0.0
                version = line.split('"')[1]
                return version

    raise RuntimeError(f"Could not find RGFX_VERSION in {version_h}")


def sha256_file(filepath):
    """Calculate SHA256 hash of a file"""
    sha256_hash = hashlib.sha256()
    with open(filepath, "rb") as f:
        for byte_block in iter(lambda: f.read(4096), b""):
            sha256_hash.update(byte_block)
    return sha256_hash.hexdigest()


def generate_manifest(hub_firmware_dir, version):
    """Generate manifest.json for USB serial flashing"""
    manifest_path = hub_firmware_dir / 'manifest.json'

    # Files for serial flashing (Hub uses firmware.bin, bootloader.bin, partitions.bin)
    files_info = []

    # Define files with their flash addresses
    flash_files = [
        {'name': 'bootloader.bin', 'address': 4096},
        {'name': 'partitions.bin', 'address': 32768},
        {'name': 'firmware.bin', 'address': 65536},
    ]

    for file_info in flash_files:
        file_path = hub_firmware_dir / file_info['name']

        if not file_path.exists():
            raise RuntimeError(f"Required file not found: {file_path}")

        file_size = file_path.stat().st_size
        file_sha256 = sha256_file(file_path)

        files_info.append({
            'name': file_info['name'],
            'address': file_info['address'],
            'size': file_size,
            'sha256': file_sha256
        })

    # Get firmware binary SHA256 specifically
    firmware_sha256 = next(f['sha256'] for f in files_info if f['name'] == 'firmware.bin')

    manifest = {
        'version': version,
        'generatedAt': datetime.now(timezone.utc).isoformat(),
        'firmwareBinarySha256': firmware_sha256,
        'files': files_info
    }

    manifest_path.write_text(json.dumps(manifest, indent=2) + '\n')
    print(f"  ✓ manifest.json generated (version {version})")


def copy_to_hub_public(project_root, build_dir):
    """
    Copy firmware files to Hub's public folder with versioned filename.

    Creates two copies of firmware for different flash methods:
    - firmware.bin: Used by USB serial flasher (referenced in manifest.json)
    - rgfx-firmware.{version}.bin: Used by OTA flasher (detected by FirmwareVersionService)

    Both files are IDENTICAL (same SHA256) to ensure consistency across flash methods.
    The manifest.json is auto-generated with checksums to ensure integrity.
    """
    hub_firmware_dir = project_root / 'rgfx-hub' / 'assets' / 'esp32' / 'firmware'
    hub_firmware_dir.mkdir(parents=True, exist_ok=True)

    version = get_version(project_root)

    print("\nCopying files to rgfx-hub/assets/esp32/firmware:")

    # Delete all old rgfx-firmware.*.bin files
    for old_file in hub_firmware_dir.glob('rgfx-firmware.*.bin'):
        old_file.unlink()
        print(f"  ✗ Deleted old firmware: {old_file.name}")

    # Copy firmware.bin (required for USB serial flashing via manifest.json)
    firmware_bin_path = build_dir / 'firmware.bin'
    if firmware_bin_path.exists():
        # Copy as firmware.bin for USB serial flashing
        dest_firmware = hub_firmware_dir / 'firmware.bin'
        dest_firmware.write_bytes(firmware_bin_path.read_bytes())
        print(f"  ✓ firmware.bin ({dest_firmware.stat().st_size} bytes)")

        # Also copy with version in filename for OTA updates
        versioned_firmware = hub_firmware_dir / f'rgfx-firmware.{version}.bin'
        versioned_firmware.write_bytes(firmware_bin_path.read_bytes())
        print(f"  ✓ {versioned_firmware.name} ({versioned_firmware.stat().st_size} bytes)")
    else:
        print(f"  ✗ firmware.bin not found at {firmware_bin_path}")

    # Copy other required flash files
    for file_info in FIRMWARE_FILES:
        if file_info['name'] == 'firmware.bin':
            continue  # Already handled above

        source_path = build_dir / file_info['name']
        dest_path = hub_firmware_dir / file_info['name']

        if source_path.exists():
            dest_path.write_bytes(source_path.read_bytes())
            print(f"  ✓ {file_info['name']} ({dest_path.stat().st_size} bytes)")
        else:
            print(f"  ✗ {file_info['name']} not found at {source_path}")

    # Generate manifest.json for USB serial flashing
    generate_manifest(hub_firmware_dir, version)

    print(f"Firmware v{version} copied to Hub public folder\n")


def copy_firmware_standalone():
    """Copy compiled firmware and required flash files to esp32-installer folder (standalone mode)"""
    # Get project root (script is in esp32/, project root is parent)
    script_dir = Path(__file__).parent
    project_root = script_dir.parent

    # Detect build directory
    build_dir = script_dir / '.pio' / 'build' / 'rgfx-driver'

    if not build_dir.exists():
        print(f"Build directory not found: {build_dir}")
        print("Run 'pio run' first to build the firmware")
        return

    # Destination directory for standalone installer
    installer_dir = project_root / 'esp32-installer'
    installer_dir.mkdir(parents=True, exist_ok=True)

    # Files to copy with their sources
    files_to_copy = {
        'firmware.bin': build_dir / 'firmware.bin',
        'bootloader.bin': build_dir / 'bootloader.bin',
        'partitions.bin': build_dir / 'partitions.bin',
    }

    print("Copying files to esp32-installer:")
    for dest_name, source_path in files_to_copy.items():
        dest_path = installer_dir / dest_name
        if source_path.exists():
            shutil.copy2(source_path, dest_path)
            print(f"  ✓ {dest_name}")
        else:
            print(f"  ✗ {dest_name} not found at {source_path}")

    # Check if boot_app0.bin exists in installer dir (should be there from git)
    boot_app0_path = installer_dir / 'boot_app0.bin'
    if boot_app0_path.exists():
        print(f"  ✓ boot_app0.bin (already present)")

    print("All files copied successfully!\n")

    # Also copy to Hub public folder
    copy_to_hub_public(project_root, build_dir)


def copy_firmware_pio(source, target, env):
    """Copy compiled firmware and required flash files to esp32-installer folder (PlatformIO callback)"""
    # Get paths from environment
    firmware_source = str(target[0])
    build_dir = Path(firmware_source).parent

    # Get project root (parent of esp32 folder)
    project_root = Path(env['PROJECT_DIR']).parent
    installer_dir = project_root / 'esp32-installer'

    # Files to copy with their sources
    files_to_copy = {
        'firmware.bin': Path(firmware_source),
        'bootloader.bin': build_dir / 'bootloader.bin',
        'partitions.bin': build_dir / 'partitions.bin',
    }

    # boot_app0.bin is only available during serial uploads, not OTA
    if 'FLASH_EXTRA_IMAGES' in env:
        files_to_copy['boot_app0.bin'] = Path(env['FLASH_EXTRA_IMAGES'][2][1])

    print("\nCopying files to esp32-installer:")
    for dest_name, source_path in files_to_copy.items():
        dest_path = installer_dir / dest_name
        if source_path.exists():
            shutil.copy2(source_path, dest_path)
            print(f"  ✓ {dest_name}")
        else:
            print(f"  ✗ {dest_name} not found at {source_path}")

    # Check if boot_app0.bin exists in installer dir (should be there from git)
    boot_app0_path = installer_dir / 'boot_app0.bin'
    if boot_app0_path.exists() and 'boot_app0.bin' not in files_to_copy:
        print(f"  ✓ boot_app0.bin (already present)")

    print("All files copied successfully!\n")

    # Also copy to Hub public folder
    copy_to_hub_public(project_root, build_dir)

# Detect if running standalone or as PlatformIO script
if __name__ == "__main__":
    # Standalone mode - called directly from command line or CI
    copy_firmware_standalone()
else:
    # PlatformIO mode - called as extra script
    Import("env")
    # Register the callback to run after build
    env.AddPostAction("$BUILD_DIR/${PROGNAME}.bin", copy_firmware_pio)
