#!/usr/bin/env python3
"""
Firmware Build Post-Processing Script

Copies compiled ESP32 firmware files to:
1. esp32-installer/ (for serial flashing via esptool)
2. rgfx-hub/assets/esp32/firmware/ (for OTA updates from Hub)

Supports multiple chip variants (ESP32, ESP32-S3) with chip-specific firmware files
and a unified manifest containing all variants.

This script runs automatically after PlatformIO builds via extra_scripts in platformio.ini.
Can also be run standalone for manual deployment.
"""

import shutil
import hashlib
import json
from datetime import datetime, timezone
from pathlib import Path

# Chip variant configurations
# Maps PlatformIO environment name to chip type identifier
CHIP_VARIANTS = {
    'rgfx-driver': {
        'chip': 'ESP32',
        'bootloader_address': 0x1000,  # ESP32 bootloader at 0x1000
    },
    'rgfx-driver-s3': {
        'chip': 'ESP32-S3',
        'bootloader_address': 0x0,  # ESP32-S3 bootloader at 0x0
    },
}

# Common flash addresses (same for all variants except bootloader)
PARTITIONS_ADDRESS = 0x8000
FIRMWARE_ADDRESS = 0x10000


def files_are_identical(src: Path, dest: Path) -> bool:
    """Check if two files have identical content"""
    if not dest.exists():
        return False
    return src.read_bytes() == dest.read_bytes()


def should_update_manifest(manifest_path: Path, new_variants: dict) -> bool:
    """Check if manifest content changed (ignoring timestamp)"""
    if not manifest_path.exists():
        return True

    try:
        old_manifest = json.loads(manifest_path.read_text())
        # Compare variants only (ignore generatedAt)
        return old_manifest.get('variants') != new_variants
    except (json.JSONDecodeError, IOError):
        return True


def get_version(project_root):
    """Extract version from version.h header file (generated by inject_version.py)"""
    version_h = project_root / 'esp32' / 'src' / 'version.h'

    # Read version.h and extract RGFX_VERSION value
    with open(version_h, 'r') as f:
        for line in f:
            if line.startswith('#define RGFX_VERSION'):
                # Extract version string: #define RGFX_VERSION "1.0.0" -> 1.0.0
                version = line.split('"')[1]
                return version

    raise RuntimeError(f"Could not find RGFX_VERSION in {version_h}")


def sha256_file(filepath):
    """Calculate SHA256 hash of a file"""
    sha256_hash = hashlib.sha256()
    with open(filepath, "rb") as f:
        for byte_block in iter(lambda: f.read(4096), b""):
            sha256_hash.update(byte_block)
    return sha256_hash.hexdigest()


def get_file_info(filepath, address):
    """Get file metadata for manifest"""
    return {
        'name': filepath.name,
        'address': address,
        'size': filepath.stat().st_size,
        'sha256': sha256_file(filepath),
    }


def get_variant_version(hub_firmware_dir, chip_suffix):
    """
    Get the version for a specific chip variant from its versioned firmware file.

    Looks for files matching pattern: rgfx-firmware-{chip_suffix}.{version}.bin
    Returns the version string, or None if not found.
    """
    pattern = f'rgfx-firmware-{chip_suffix}.*.bin'
    matches = list(hub_firmware_dir.glob(pattern))

    if not matches:
        return None

    # Should only be one versioned file per variant (old ones are deleted on build)
    versioned_file = matches[0]

    # Extract version from filename: rgfx-firmware-esp32s3.0.1.0-dev+hash.bin -> 0.1.0-dev+hash
    filename = versioned_file.name
    prefix = f'rgfx-firmware-{chip_suffix}.'
    suffix = '.bin'

    if filename.startswith(prefix) and filename.endswith(suffix):
        version = filename[len(prefix):-len(suffix)]
        return version

    return None


def generate_multi_chip_manifest(hub_firmware_dir, current_build_version, current_build_chip=None):
    """
    Generate manifest.json with all chip variants.

    Each variant tracks its own version independently, extracted from the
    versioned firmware filename. This allows building variants at different
    times without incorrectly flagging other variants as needing updates.

    Manifest structure:
    {
        "generatedAt": "...",
        "variants": {
            "ESP32": {
                "version": "0.1.0-dev+abc123",
                "files": [...]
            },
            "ESP32-S3": {
                "version": "0.1.0-dev+def456",
                "files": [...]
            }
        }
    }
    """
    manifest_path = hub_firmware_dir / 'manifest.json'

    variants = {}

    for env_name, config in CHIP_VARIANTS.items():
        chip = config['chip']
        chip_suffix = chip.lower().replace('-', '')  # "ESP32-S3" -> "esp32s3"

        # Check if this variant's firmware exists
        firmware_file = hub_firmware_dir / f'firmware-{chip_suffix}.bin'
        bootloader_file = hub_firmware_dir / f'bootloader-{chip_suffix}.bin'
        partitions_file = hub_firmware_dir / f'partitions-{chip_suffix}.bin'

        if not firmware_file.exists():
            print(f"  ⚠ Skipping {chip} variant (not built yet)")
            continue

        # Get version for this specific variant
        # If this is the variant we just built, use current_build_version
        # Otherwise, extract from existing versioned filename
        if current_build_chip and chip == current_build_chip:
            variant_version = current_build_version
        else:
            variant_version = get_variant_version(hub_firmware_dir, chip_suffix)
            if not variant_version:
                # Fallback to current build version if no versioned file exists
                variant_version = current_build_version
                print(f"  ⚠ {chip}: No versioned file found, using current build version")

        files_info = []

        # Bootloader (chip-specific address)
        if bootloader_file.exists():
            files_info.append(get_file_info(bootloader_file, config['bootloader_address']))

        # Partitions (common address)
        if partitions_file.exists():
            files_info.append(get_file_info(partitions_file, PARTITIONS_ADDRESS))

        # Firmware (common address)
        files_info.append(get_file_info(firmware_file, FIRMWARE_ADDRESS))

        variants[chip] = {
            'version': variant_version,
            'files': files_info
        }

        print(f"  ✓ {chip} variant added to manifest (v{variant_version})")

    if not variants:
        raise RuntimeError("No firmware variants found to include in manifest")

    # Only update manifest if variants changed (ignore timestamp)
    if should_update_manifest(manifest_path, variants):
        manifest = {
            'generatedAt': datetime.now(timezone.utc).isoformat(),
            'variants': variants,
        }
        manifest_path.write_text(json.dumps(manifest, indent=2) + '\n')
        print(f"  ✓ manifest.json updated ({len(variants)} variant(s))")
    else:
        print(f"  ○ manifest.json unchanged (skipped)")


def copy_variant_to_hub(project_root, build_dir, env_name):
    """
    Copy a single chip variant's firmware files to Hub's public folder.

    Files are named with chip suffix:
    - firmware-esp32.bin, bootloader-esp32.bin, partitions-esp32.bin
    - firmware-esp32s3.bin, bootloader-esp32s3.bin, partitions-esp32s3.bin
    """
    if env_name not in CHIP_VARIANTS:
        print(f"  ⚠ Unknown environment {env_name}, skipping Hub copy")
        return

    config = CHIP_VARIANTS[env_name]
    chip = config['chip']
    chip_suffix = chip.lower().replace('-', '')  # "ESP32-S3" -> "esp32s3"

    hub_firmware_dir = project_root / 'rgfx-hub' / 'assets' / 'esp32' / 'firmware'
    hub_firmware_dir.mkdir(parents=True, exist_ok=True)

    print(f"\nCopying {chip} firmware to rgfx-hub/assets/esp32/firmware:")

    # Files to copy with chip-specific names
    files_to_copy = [
        ('firmware.bin', f'firmware-{chip_suffix}.bin'),
        ('bootloader.bin', f'bootloader-{chip_suffix}.bin'),
        ('partitions.bin', f'partitions-{chip_suffix}.bin'),
    ]

    for src_name, dest_name in files_to_copy:
        source_path = build_dir / src_name
        dest_path = hub_firmware_dir / dest_name

        if source_path.exists():
            if files_are_identical(source_path, dest_path):
                print(f"  ○ {dest_name} unchanged (skipped)")
            else:
                dest_path.write_bytes(source_path.read_bytes())
                print(f"  ✓ {dest_name} ({dest_path.stat().st_size} bytes)")
        else:
            print(f"  ✗ {src_name} not found at {source_path}")

    # Also copy versioned firmware for OTA (chip-specific)
    version = get_version(project_root)
    firmware_src = build_dir / 'firmware.bin'
    if firmware_src.exists():
        versioned_name = f'rgfx-firmware-{chip_suffix}.{version}.bin'
        versioned_path = hub_firmware_dir / versioned_name

        if files_are_identical(firmware_src, versioned_path):
            print(f"  ○ {versioned_name} unchanged (skipped)")
        else:
            # Delete old versioned files for this chip (only if creating new one)
            for old_file in hub_firmware_dir.glob(f'rgfx-firmware-{chip_suffix}.*.bin'):
                old_file.unlink()
                print(f"  ✗ Deleted old: {old_file.name}")

            versioned_path.write_bytes(firmware_src.read_bytes())
            print(f"  ✓ {versioned_name} ({versioned_path.stat().st_size} bytes)")

    # Regenerate manifest with all available variants
    # Pass the chip we just built so its version is taken from current build
    generate_multi_chip_manifest(hub_firmware_dir, version, current_build_chip=chip)

    print(f"{chip} firmware v{version} copied to Hub\n")


def copy_to_installer(project_root, build_dir, env_name):
    """Copy firmware files to esp32-installer folder for serial flashing"""
    if env_name not in CHIP_VARIANTS:
        return

    config = CHIP_VARIANTS[env_name]
    chip_suffix = config['chip'].lower().replace('-', '')

    installer_dir = project_root / 'esp32-installer'
    installer_dir.mkdir(parents=True, exist_ok=True)

    files_to_copy = {
        f'firmware-{chip_suffix}.bin': build_dir / 'firmware.bin',
        f'bootloader-{chip_suffix}.bin': build_dir / 'bootloader.bin',
        f'partitions-{chip_suffix}.bin': build_dir / 'partitions.bin',
    }

    print(f"Copying {config['chip']} files to esp32-installer:")
    for dest_name, source_path in files_to_copy.items():
        dest_path = installer_dir / dest_name
        if source_path.exists():
            shutil.copy2(source_path, dest_path)
            print(f"  ✓ {dest_name}")
        else:
            print(f"  ✗ {dest_name} not found at {source_path}")


def copy_firmware_standalone():
    """Copy compiled firmware for all built environments (standalone mode)"""
    script_dir = Path(__file__).parent
    project_root = script_dir.parent

    print("Copying firmware files (standalone mode)\n")

    for env_name in CHIP_VARIANTS.keys():
        build_dir = script_dir / '.pio' / 'build' / env_name

        if not build_dir.exists():
            print(f"Skipping {env_name} (not built)")
            continue

        copy_to_installer(project_root, build_dir, env_name)
        copy_variant_to_hub(project_root, build_dir, env_name)

    # Check if boot_app0.bin exists in installer dir
    installer_dir = project_root / 'esp32-installer'
    boot_app0_path = installer_dir / 'boot_app0.bin'
    if boot_app0_path.exists():
        print(f"  ✓ boot_app0.bin (already present)")

    print("\nAll files copied successfully!")


def copy_firmware_pio(source, target, env):
    """Copy compiled firmware (PlatformIO callback - runs after each environment build)"""
    firmware_source = str(target[0])
    build_dir = Path(firmware_source).parent
    project_root = Path(env['PROJECT_DIR']).parent

    # Get environment name from build path
    env_name = build_dir.name

    print(f"\ncopy_firmware_pio([{firmware_source}], [{target[0]}])")

    copy_to_installer(project_root, build_dir, env_name)
    copy_variant_to_hub(project_root, build_dir, env_name)

    # Check if boot_app0.bin exists in installer dir
    installer_dir = project_root / 'esp32-installer'
    boot_app0_path = installer_dir / 'boot_app0.bin'
    if boot_app0_path.exists():
        print(f"  ✓ boot_app0.bin (already present)")


# Detect if running standalone or as PlatformIO script
if __name__ == "__main__":
    copy_firmware_standalone()
else:
    Import("env")
    env.AddPostAction("$BUILD_DIR/${PROGNAME}.bin", copy_firmware_pio)
