#!/usr/bin/env python3
"""
Convert HTML files to C++ PROGMEM headers for ESP32

This script reads HTML template files and converts them to C++ header files
with the HTML content stored in PROGMEM (flash memory) to save RAM.

Usage:
    python3 html_to_progmem.py

The script looks for all .html files in the html/ directory and generates
corresponding .h files in src/generated/
"""

import os
import re
from pathlib import Path


def sanitize_variable_name(filename):
    """Convert filename to valid C++ variable name"""
    # Remove extension and convert to uppercase with underscores
    name = Path(filename).stem
    name = re.sub(r'[^a-zA-Z0-9_]', '_', name)
    return name.upper()


def html_to_progmem(html_file, output_file):
    """Convert HTML file to C++ header with PROGMEM"""

    # Read HTML content
    with open(html_file, 'r', encoding='utf-8') as f:
        html_content = f.read()

    # Minify HTML (remove extra whitespace while preserving structure)
    html_content = re.sub(r'\n\s*', '\n', html_content)  # Remove leading whitespace
    html_content = re.sub(r'\n+', '\n', html_content)    # Remove multiple newlines
    html_content = html_content.strip()                   # Remove leading/trailing whitespace

    # Get variable name from filename
    var_name = sanitize_variable_name(html_file)

    # Generate C++ header content
    header_content = f"""/* Auto-generated file - DO NOT EDIT MANUALLY
 * Generated from: {os.path.basename(html_file)}
 *
 * This file is automatically generated by html_to_progmem.py
 * Any manual changes will be overwritten on next build.
 */

#ifndef HTML_{var_name}_H
#define HTML_{var_name}_H

#include <Arduino.h>

// HTML template stored in PROGMEM (flash memory)
// Template variables (replace at runtime):
//   {{{{DEVICE_NAME}}}} - Device name from Utils::getDeviceName()
//   {{{{MAC_ADDRESS}}}} - MAC address from WiFi.macAddress()
//   {{{{UPTIME}}}} - Uptime in seconds
//   {{{{NETWORK_STATUS}}}} - Network status table rows (dynamic)
//   {{{{LED_BRIGHTNESS}}}} - LED brightness value
//   {{{{LED_DATA_PIN}}}} - LED data pin number

const char HTML_{var_name}[] PROGMEM = R"rawliteral(
{html_content}
)rawliteral";

#endif // HTML_{var_name}_H
"""

    # Write output file
    os.makedirs(os.path.dirname(output_file), exist_ok=True)
    with open(output_file, 'w', encoding='utf-8') as f:
        f.write(header_content)

    print(f"Generated: {output_file}")
    return output_file


def main():
    """Process all HTML files in html/ directory"""
    script_dir = Path(__file__).parent
    html_dir = script_dir / 'html'
    output_dir = script_dir / 'src' / 'generated'

    if not html_dir.exists():
        print(f"Error: HTML directory not found: {html_dir}")
        return 1

    # Find all .html files
    html_files = list(html_dir.glob('*.html'))

    if not html_files:
        print(f"No .html files found in {html_dir}")
        return 0

    print(f"Converting {len(html_files)} HTML file(s) to PROGMEM headers...")

    # Process each HTML file
    for html_file in html_files:
        output_file = output_dir / f"html_{html_file.stem}.h"
        html_to_progmem(str(html_file), str(output_file))

    print("Done!")
    return 0


if __name__ == '__main__':
    exit(main())
