; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:rgfx-node]
platform = espressif32
board = esp32dev
framework = arduino

; Serial Monitor settings
monitor_speed = 115200
monitor_filters = esp32_exception_decoder, colorize, send_on_enter
monitor_rts = 0
monitor_dtr = 0
monitor_echo = yes

; Upload settings
upload_speed = 921600
upload_port = /dev/cu.usbserial-0001
upload_flags =
    --before=default_reset
    --after=hard_reset

; Libraries (add as needed for your project)
lib_deps =
    fastled/FastLED@^3.6.0
    knolleary/PubSubClient@^2.8
    bblanchon/ArduinoJson@^7.0.0
    https://github.com/prampec/IotWebConf.git#v3.2.2

; Post-build script to copy firmware to installer folder
extra_scripts = post:copy_firmware.py
