#!/usr/bin/env python3
"""
Extract bitmap data from DEN 8x8 OTF font and generate C++ header.

Usage: python3 extract_font.py
Output: ../src/fonts/den_8x8.cpp
"""

from PIL import Image, ImageDraw, ImageFont
import os

FONT_PATH = os.path.join(os.path.dirname(__file__), "den-8x8.otf")
OUTPUT_DIR = os.path.join(os.path.dirname(__file__), "..", "..", "src", "fonts")

# Characters to extract (printable ASCII)
CHARS = [chr(i) for i in range(32, 127)]  # space (32) through tilde (126)

def extract_glyph(font, char, size=8):
    """Render a character and extract its bitmap rows."""
    # Create image slightly larger than needed to capture the glyph
    img = Image.new('L', (size, size), 0)
    draw = ImageDraw.Draw(img)

    # Draw character at origin
    draw.text((0, 0), char, font=font, fill=255)

    # Extract 7 rows (skip bottom row which is typically blank for spacing)
    rows = []
    for y in range(7):
        row_byte = 0
        for x in range(8):
            if x < img.width and y < img.height:
                pixel = img.getpixel((x, y))
                if pixel > 127:  # Threshold for 1-bit
                    row_byte |= (1 << (7 - x))  # MSB = leftmost pixel
        rows.append(row_byte)

    return rows

def generate_cpp(glyphs):
    """Generate C++ source file with font data."""
    lines = [
        "/**",
        " * DEN 8x8 bitmap font",
        " * Created by denzel5310",
        " * https://www.fontstruct.com/fontstructions/show/2784534",
        " * Licensed under CC0 Public Domain Dedication",
        " *",
        " * Auto-generated by extract_font.py - do not edit manually",
        " */",
        "",
        '#include "den_8x8.h"',
        "",
        "namespace {",
        "",
        "// 7 bytes per character (7 rows, MSB = leftmost pixel)",
        "// Characters 32 (space) through 126 (tilde)",
        "const uint8_t FONT_DATA[] PROGMEM = {",
    ]

    for char, rows in glyphs:
        if char == '\\':
            char_display = '\\\\'
        elif char == "'":
            char_display = "\\'"
        else:
            char_display = char

        hex_bytes = ", ".join(f"0x{b:02X}" for b in rows)
        lines.append(f"    {hex_bytes},  // '{char_display}' ({ord(char)})")

    lines.extend([
        "};",
        "",
        "}  // namespace",
        "",
        "const uint8_t* getGlyph(char c) {",
        "    if (c < 32 || c > 126) {",
        "        return nullptr;",
        "    }",
        "    return &FONT_DATA[(c - 32) * 7];",
        "}",
        "",
    ])

    return "\n".join(lines)

def generate_header():
    """Generate C++ header file."""
    return """/**
 * DEN 8x8 bitmap font
 * Created by denzel5310
 * https://www.fontstruct.com/fontstructions/show/2784534
 * Licensed under CC0 Public Domain Dedication
 */

#pragma once

#include <stdint.h>
#ifdef ARDUINO
#include <pgmspace.h>
#else
#define PROGMEM
#define pgm_read_byte(addr) (*(const uint8_t*)(addr))
#endif

constexpr uint8_t FONT_CHAR_WIDTH = 8;
constexpr uint8_t FONT_CHAR_HEIGHT = 7;

// Returns pointer to 7 bytes of glyph data, or nullptr if char not in font
const uint8_t* getGlyph(char c);
"""

def main():
    # Load font
    font = ImageFont.truetype(FONT_PATH, 8)

    # Extract all glyphs
    glyphs = []
    for char in CHARS:
        rows = extract_glyph(font, char)
        glyphs.append((char, rows))

    # Create output directory
    os.makedirs(OUTPUT_DIR, exist_ok=True)

    # Write header
    header_path = os.path.join(OUTPUT_DIR, "den_8x8.h")
    with open(header_path, 'w') as f:
        f.write(generate_header())
    print(f"Generated: {header_path}")

    # Write source
    cpp_path = os.path.join(OUTPUT_DIR, "den_8x8.cpp")
    with open(cpp_path, 'w') as f:
        f.write(generate_cpp(glyphs))
    print(f"Generated: {cpp_path}")

    # Print stats
    total_bytes = len(glyphs) * 7
    print(f"Font data: {len(glyphs)} characters, {total_bytes} bytes")

if __name__ == "__main__":
    main()
