# RGFX Documentation
# https://squidfunk.github.io/mkdocs-material/

site_name: RGFX Documentation
site_url: https://rgfx.io/
site_description: Retro Game Effects - External visual effects for retro video games

theme:
  name: material
  favicon: assets/images/favicon.png
  palette:
    scheme: slate
    primary: grey
    accent: light blue
  features:
    - navigation.top
    - search.highlight
    - content.code.copy

plugins:
  - search
  - offline
  - open-in-new-tab

# Disable features incompatible with file:// protocol
use_directory_urls: false

nav:
  - Overview:
    - Introduction: overview/index.md
    - Requirements: overview/requirements.md
    - Getting Started: overview/getting-started.md
    - Architecture: overview/architecture.md
  - Interceptors:
    - Introduction: interceptors/index.md
  - Transformers:
    - Introduction: transformers/index.md
  - ESP32 Hardware:
    - Introduction: esp32/index.md

markdown_extensions:
  - attr_list
  - mdx_truly_sane_lists
  - admonition
  - pymdownx.details
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - toc:
      permalink: true

extra_css:
  - assets/css/custom.css

extra_javascript:
  - assets/js/mermaid.min.js
